name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    # Step to install project dependencies
    - name: Install dependencies using Makefile
      run: |
        make install

    # Step to run the Flask server and sleep for 5 seconds to allow server to start
    - name: Run the Flask app and wait for server startup
      run: |
        make run &
        sleep 5  # Ensure the server has time to start up
